# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.data_pb2 as data__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModuleBStub(object):
    """Service run by Module B
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessEvent = channel.unary_unary(
                '/pipeline.ModuleB/ProcessEvent',
                request_serializer=data__pb2.Event.SerializeToString,
                response_deserializer=data__pb2.BasicResponse.FromString,
                _registered_method=True)


class ModuleBServicer(object):
    """Service run by Module B
    """

    def ProcessEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessEvent,
                    request_deserializer=data__pb2.Event.FromString,
                    response_serializer=data__pb2.BasicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.ModuleB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.ModuleB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleB(object):
    """Service run by Module B
    """

    @staticmethod
    def ProcessEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.ModuleB/ProcessEvent',
            data__pb2.Event.SerializeToString,
            data__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModuleCStub(object):
    """Service run by Module C
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TextToSpeech = channel.unary_unary(
                '/pipeline.ModuleC/TextToSpeech',
                request_serializer=data__pb2.Comment.SerializeToString,
                response_deserializer=data__pb2.BasicResponse.FromString,
                _registered_method=True)


class ModuleCServicer(object):
    """Service run by Module C
    """

    def TextToSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TextToSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.TextToSpeech,
                    request_deserializer=data__pb2.Comment.FromString,
                    response_serializer=data__pb2.BasicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.ModuleC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.ModuleC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleC(object):
    """Service run by Module C
    """

    @staticmethod
    def TextToSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.ModuleC/TextToSpeech',
            data__pb2.Comment.SerializeToString,
            data__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModuleDStub(object):
    """Service run by Module D
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayAudio = channel.unary_unary(
                '/pipeline.ModuleD/PlayAudio',
                request_serializer=data__pb2.Audio.SerializeToString,
                response_deserializer=data__pb2.BasicResponse.FromString,
                _registered_method=True)


class ModuleDServicer(object):
    """Service run by Module D
    """

    def PlayAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleDServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayAudio,
                    request_deserializer=data__pb2.Audio.FromString,
                    response_serializer=data__pb2.BasicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.ModuleD', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.ModuleD', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleD(object):
    """Service run by Module D
    """

    @staticmethod
    def PlayAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.ModuleD/PlayAudio',
            data__pb2.Audio.SerializeToString,
            data__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
