services:
  game:
    build: ./game
    volumes:
      - ./game:/workspace/game:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie:ro
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/snd:/dev/snd"
    environment:
      - DISPLAY=${DISPLAY}

  commentary:
    build: ./commentary
    volumes:
      - ./commentary:/workspace/commentary:cached
      - ./protos:/workspace/protos:ro
    ports:
      - "50051:50051"
    depends_on:
      - game
    command: ["python", "app.py"]

  tts:
    build: ./tts
    volumes:
      - ./tts:/workspace/tts:cached
      - ./protos:/workspace/protos:ro
    ports:
      - "50052:50052"
    depends_on:
      - commentary
    command: ["python", "app.py"]